version: 2.1
jobs:
  test-stage1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: make test
      - "slack/status":
          fail_only: false
  test-stage2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: make test-stage2
      - "slack/status":
          fail_only: false
  test-stage3:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: make test-stage3
      - "slack/status":
          fail_only: false
  nqueen:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: make test-nqueen
      - "slack/status":
          fail_only: false
  dp:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: make test-dp
      - "slack/status":
          fail_only: false

orbs:
  slack: circleci/slack@3.4.2
workflows:
  wfs:
    jobs:
      - test-stage1
      - test-stage2
      - test-stage3
